# theme = "hyde"
# theme = "strange-case"
theme = "hyde-pb"
languageCode = "en-us"
title = "The Plone Expanse"
description ="Zope/Plone tips and tutorial, by Tiberiu Ichim"
baseurl = "/"
Paginate = 10

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    blog = "/blog/:year/:month/:day/:title/"

[params]
    Author = "Tiberiu Ichim"
    Description = "My thoughts, rants and tutorials on programming with a focus on the Plone, Zope and a dash of everything else"
    Copyright = "@2016 Tiberiu Ichim"

    layoutReverse = true
    disqusShortName = "play-pixelblaster-ro"
    # themeColor = "theme-base-08"

[[menu.main]]
    name = "Github"
    post = "<i class='fa fa-github-alt' aria-hidden='true'></i>"
    url = "https://github.com/tiberiuichim"

[taxonomies]
    tag = "tags"
